kleides_mfa/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = 'kleides_mfa'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('list/', views.DeviceListView.as_view(), name='index'),
    path(
        '<slug:plugin>/create/', views.DeviceCreateView.as_view(),
        name='create'),
    path(
        '<slug:plugin>/update/<int:device_id>/',
        views.DeviceUpdateView.as_view(), name='update'),
    path(
        '<slug:plugin>/verify/<int:device_id>/',
        views.DeviceVerifyView.as_view(), name='verify'),
    path(
        '<slug:plugin>/delete/<int:device_id>/',
        views.DeviceDeleteView.as_view(), name='delete'),
]

kleides_mfa/views/device.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelform_factory
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    CreateView, DeleteView, TemplateView, UpdateView)

from ..forms import DeviceUpdateForm
from ..registry import registry


class DeviceListView(LoginRequiredMixin, TemplateView):
    template_name = 'kleides_mfa/plugin_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plugins'] = registry.plugins_with_user_devices(
            self.request.user, confirmed=None)
        return context


class PluginMixin():
    success_url = reverse_lazy('kleides_mfa:index')

    def dispatch(self, *args, **kwargs):
        self.plugin = self.get_plugin()
        return super().dispatch(*args, **kwargs)

    def get_plugin(self):
        try:
            return registry.get_plugin(self.kwargs['plugin'])
        except KeyError:
            raise Http404('Plugin does not exist')

    def get_object(self):
        return self.plugin.get_user_device(
            self.kwargs['device_id'], self.request.user, confirmed=None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plugin'] = self.plugin
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['plugin'] = self.plugin
        kwargs['request'] = self.request
        return kwargs

    def get_template_names(self):
        return [
            'kleides_mfa/device_{}{}.html'.format(
                self.plugin.slug, self.template_name_suffix),
            'kleides_mfa/device{}.html'.format(self.template_name_suffix),
        ]


class DeviceCreateView(LoginRequiredMixin, PluginMixin, CreateView):
    template_name_suffix = '_create_form'

    def get_form_class(self):
        if self.plugin.create_form is None:
            raise Http404(
                'Plugin {} does not support this'.format(self.plugin))
        return self.plugin.create_form


class DeviceUpdateView(LoginRequiredMixin, PluginMixin, UpdateView):
    def get_form_class(self):
        if self.plugin.update_form is None:
            return modelform_factory(
                self.plugin.model, form=DeviceUpdateForm, fields=('name',))
        return self.plugin.update_form


class DeviceDeleteView(LoginRequiredMixin, PluginMixin, DeleteView):
    # XXX notification via email ?
    # XXX password confirmation ?
    def delete(self, request, *args, **kwargs):
        message = _(
            'The {plugin} "{name}" was deleted successfully.').format(
                plugin=self.plugin, name=self.get_object().name)
        response = super().delete(request, *args, **kwargs)
        messages.warning(request, message)
        return response

kleides_mfa/views/devices.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.http import Http404
from django.utils import timezone
from django.views.generic import (
    CreateView, DeleteView, TemplateView, UpdateView)

from django_otp import DEVICE_ID_SESSION_KEY, login as django_otp_login

from ..registry import registry
from ..signals import mfa_added, mfa_removed
from .mixins import (
    VERIFIED_SESSION_KEY, PluginMixin, RecentMultiFactorRequiredMixin,
    SetupOrMFARequiredMixin, SetupOrRecentMFARequiredMixin)


class DeviceListView(SetupOrMFARequiredMixin, TemplateView):
    template_name = 'kleides_mfa/plugin_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plugins'] = registry.plugins_with_user_devices(
            self.request.user, confirmed=None)
        return context


class DeviceCreateView(SetupOrRecentMFARequiredMixin, PluginMixin, CreateView):
    template_name_suffix = '_create_form'

    def get_form_class(self):
        form_class = self.plugin.get_create_form_class()
        if form_class is None:
            raise Http404(
                'Plugin {} does not support this'.format(self.plugin))
        return form_class

    def form_valid(self, form):
        response = super().form_valid(form)
        # This is the users first device, use it to verify the user.
        if not self.request.user.is_verified:
            django_otp_login(self.request, self.object)
            # Add the last verification time to the session.
            # Note that the verified session parameters should match the
            # session when authenticating in DeviceVerifyView.
            self.request.session[
                VERIFIED_SESSION_KEY] = timezone.now().isoformat()
        messages.success(
            self.request, self.plugin.get_create_message(self.object))
        mfa_added.send(
            sender=__name__, instance=self.object, request=self.request)
        return response


class DeviceUpdateView(
        RecentMultiFactorRequiredMixin, PluginMixin, UpdateView):
    def get_form_class(self):
        return self.plugin.get_update_form_class()

    def form_valid(self, form):
        messages.success(
            self.request, self.plugin.get_update_message(self.object))
        return super().form_valid(form)


class DeviceDeleteView(
        RecentMultiFactorRequiredMixin, PluginMixin, DeleteView):
    def get_form_class(self):
        return self.plugin.get_delete_form_class()

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        mfa_removed.send(sender=__name__, instance=obj, request=request)
        message = self.plugin.get_delete_message(obj)
        response = super().post(request, *args, **kwargs)
        messages.warning(request, message)
        # User has removed all authentication methods, disable his access.
        if not registry.user_has_device(self.request.user, confirmed=True):
            self.request.user.otp_device = None
            if DEVICE_ID_SESSION_KEY in self.request.session:
                del self.request.session[DEVICE_ID_SESSION_KEY]

        return response

kleides_mfa/views/mixins.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (
    get_user_model, load_backend, mixins as auth_mixins)
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.crypto import constant_time_compare
from django.utils.translation import gettext_lazy as _

from urllib.parse import urlparse

from ..conf import app_settings
from ..registry import registry


# Note that these session keys are different from django auth so the user
# session will never pass as authenticated. Meanwhile we still need to enforce
# the same protections which is the reason for the duplication.
SESSION_KEY = '_kleides-mfa_user_id'
BACKEND_SESSION_KEY = '_kleides-mfa_user_backend'
HASH_SESSION_KEY = '_kleides-mfa_user_hash'
VERIFIED_SESSION_KEY = '_kleides-mfa_user_verified'


class PluginMixin():
    success_url = reverse_lazy('kleides_mfa:index')

    def dispatch(self, *args, **kwargs):
        self.plugin = self.get_plugin()
        return super().dispatch(*args, **kwargs)

    def get_plugin(self):
        try:
            return registry.get_plugin(self.kwargs['plugin'])
        except KeyError:
            raise Http404('Plugin does not exist')

    def get_object(self):
        return self.plugin.get_user_device(
            self.kwargs['device_id'], self.request.user, confirmed=None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plugin'] = self.plugin
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['plugin'] = self.plugin
        kwargs['request'] = self.request
        return kwargs

    def get_template_names(self):
        return [
            'kleides_mfa/device_{}{}.html'.format(
                self.plugin.slug, self.template_name_suffix),
            'kleides_mfa/device{}.html'.format(self.template_name_suffix),
        ]


class UserPassesTestMixin(auth_mixins.UserPassesTestMixin):
    def handle_no_permission(self):
        '''
        Raise PermissionDenied only when raise_exception is True.
        The original implementation also raises PermissionDenied when the user
        is authenticated and fails the test. This mixin is used to force
        re-authentication for users that have exceeded the VERIFIED_TIMEOUT.
        '''
        if self.raise_exception:
            raise PermissionDenied(self.get_permission_denied_message())

        if self.request.user.is_verified:
            messages.info(
                self.request,
                _('We need to confirm your identity, please login again.'))

        path = self.request.build_absolute_uri()
        resolved_login_url = resolve_url(self.get_login_url())
        # If the login url is the same scheme and net location then use the
        # path as the "next" url.
        login_scheme, login_netloc = urlparse(resolved_login_url)[:2]
        current_scheme, current_netloc = urlparse(path)[:2]
        if (not login_scheme or login_scheme == current_scheme) and (
            not login_netloc or login_netloc == current_netloc
        ):
            path = self.request.get_full_path()
        return redirect_to_login(
            path,
            resolved_login_url,
            self.get_redirect_field_name(),
        )


class SingleFactorRequiredMixin(UserPassesTestMixin):
    '''
    Verify that the user is authenticated with a single authentication factor.
    '''
    def test_func(self):
        return self.request.user.is_single_factor_authenticated


class MultiFactorRequiredMixin(UserPassesTestMixin):
    '''
    Verify that the user is authenticated with multiple authentication factors.
    '''
    def test_func(self):
        return self.request.user.is_verified


def is_recently_verified(request):
    '''
    Verify that the user has recently verified with a authentication device.
    '''
    if request.user.is_verified:
        if app_settings.KLEIDES_MFA_VERIFIED_TIMEOUT is None:
            return True

        try:
            verified_on = datetime.fromisoformat(
                request.session[VERIFIED_SESSION_KEY])
        except (KeyError, TypeError, ValueError):
            return False

        verified_seconds = (timezone.now() - verified_on).seconds
        if verified_seconds < app_settings.KLEIDES_MFA_VERIFIED_TIMEOUT:
            if app_settings.KLEIDES_MFA_VERIFIED_UPDATE:
                (request.session
                 [VERIFIED_SESSION_KEY]) = timezone.now().isoformat()
            return True

    return False


class RecentMultiFactorRequiredMixin(UserPassesTestMixin):
    '''
    Verify that the user has recently authenticated with multiple
    authentication factors.
    '''
    def test_func(self):
        return is_recently_verified(self.request)


def is_user_in_setup(request):
    '''
    Verify that the user account is in it's initial setup stage.
    '''
    return bool(
        request.user.is_single_factor_authenticated
        and not registry.user_has_device(request.user, confirmed=True))


class SetupOrMFARequiredMixin(UserPassesTestMixin):
    '''
    Verify that the user is authenticated with multiple factors or
    with single factor and is still in the process of account setup.
    '''
    def test_func(self):
        if self.request.user.is_verified:
            return True
        return is_user_in_setup(self.request)


class SetupOrRecentMFARequiredMixin(UserPassesTestMixin):
    '''
    Verify that the user is authenticated with multiple factors or
    with single factor and is still in the process of account setup.
    '''
    def test_func(self):
        if is_recently_verified(self.request):
            return True
        return is_user_in_setup(self.request)


class UnverifiedUserMixin(UserPassesTestMixin):
    '''
    Verify that the session is associated with a User.
    Note that the user may not be fully authenticated.
    '''
    def test_func(self):
        self.unverified_user = self.get_unverified_user()
        return bool(self.unverified_user is not None)

    def get_unverified_user(self):
        '''
        Return the unverified user model instance associated with the session.
        If no user is retrieved return None.
        '''
        user = None
        try:
            user_id = get_user_model()._meta.pk.to_python(
                self.request.session[SESSION_KEY])
            backend_path = self.request.session[BACKEND_SESSION_KEY]
        except KeyError:
            pass
        else:
            if backend_path in settings.AUTHENTICATION_BACKENDS:
                backend = load_backend(backend_path)
                user = backend.get_user(user_id)
                # Verify the session
                if hasattr(user, 'get_session_auth_hash'):
                    session_hash = self.request.session.get(HASH_SESSION_KEY)
                    session_hash_verified = bool(
                        session_hash and constant_time_compare(
                            session_hash,
                            user.get_session_auth_hash()))
                    if not session_hash_verified:
                        self.request.session.flush()
                        user = None

        return user

kleides_mfa/templates/kleides_mfa/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title %}Kleides Multi Factor Authentication{% endblock %}</title>
  </head>
  <body>
    <div class="alert alert-success">
        Provide a template named <code>kleides/base.html</code> to integrate this page in your application and remove this message.
    </div>

    {% block content_wrapper %}
    <div class="container">
      {% for message in messages %}
        <div class="alert {% for tag in message.tags.split %}alert-{{ tag }} {% endfor %}alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}

      {% block content %}{% endblock %}
    </div>
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js" integrity="sha512-ubuT8Z88WxezgSqf3RLuNi5lmjstiJcyezx34yIU2gAHonIi27Na7atqzUZCOoY4CExaoFumzOsFQ2Ch+I/HCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js" integrity="sha512-XKa9Hemdy1Ui3KSGgJdgMyYlUg1gM+QhL6cnlyTe2qzMCYm4nAZ1PsVerQzTTXzonUR+dmswHqgJPuwCq1MaAg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

kleides_mfa/templates/kleides_mfa/device_confirm_delete.html
{% extends "kleides_mfa/base.html" %}

{% load i18n %}

{% block content %}
<h1>{% blocktrans with name=plugin.name %}Delete {{ name }} authentication{% endblocktrans %}</h1>

{% block form_description %}
<p>{% blocktrans with plugin=plugin.name name=object.name %}Are you sure you want to delete {{ plugin }} "{{ name }}" from your authentication methods?{% endblocktrans %}</p>
{% endblock form_description %}

<form id="kleides-mfa-delete-form" action="" method="post" novalidate>{% csrf_token %}
    <button class='btn btn-danger' type='submit'>{% trans 'Yes, I am sure' %}</button>
    <a href="{% url 'kleides_mfa:index' %}" class='btn btn-secondary'>{% trans 'No, take me back' %}</a>
</form>
{% endblock content %}

kleides_mfa/templates/kleides_mfa/device_create_form.html
{% extends "kleides_mfa/base.html" %}

{% load i18n %}

{% block content %}
<h1>{% blocktrans with name=plugin.name %}Add {{ name }} authentication{% endblocktrans %}</h1>

{% block form_description %}{% endblock form_description %}

<form id="kleides-mfa-form" action="" method="post" novalidate>{% csrf_token %}
    {% include "kleides_mfa/form.html" %}

    {% if plugin.show_create_button %}
    <button class='btn btn-primary' type='submit'>{{ plugin.create_button_label|default:_('Add') }}</button>
    {% endif %}
</form>
{% endblock content %}

kleides_mfa/templates/kleides_mfa/device_form.html
{% extends "kleides_mfa/base.html" %}

{% load i18n %}

{% block content %}
<h1>{% blocktrans with name=plugin.name %}Update {{ name }} authentication{% endblocktrans %}</h1>

{% block form_description %}{% endblock form_description %}

<form id="kleides-mfa-form" action="" method="post" novalidate>{% csrf_token %}
    {% include "kleides_mfa/form.html" %}

    <button class='btn btn-primary' type='submit'>{% trans 'Update' %}</button>
</form>
{% endblock content %}

kleides_mfa/templates/kleides_mfa/device_list.html
{% load i18n %}

<div class='position-relative'>
<a class="btn btn-primary float-right" href="{% url 'kleides_mfa:create' plugin.slug %}">{% blocktrans with name=plugin.name %}Add {{ name }}{% endblocktrans %}</a>
<h2>{{ plugin.name }}</h2>
<div class="table-responsive">
<table id="device-list" class="table table-striped">
    <thead>
        <tr>
            <th class="w-50" scope="col">{% trans 'Name' %}</th>
            <th class="w-25" scope="col">{% trans 'Confirmed' %}</th>
            <th class="w-25" scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for device in devices %}
        <tr>
            <th scope="row">{{ device.name }}</th>
            <td>{{ device.confirmed|yesno }}</td>
            <td class="text-right">
            <a class="btn btn-info" href="{% url 'kleides_mfa:update' plugin.slug device.pk %}">{% trans 'edit' %}</a>
            <a class="btn btn-danger" href="{% url 'kleides_mfa:delete' plugin.slug device.pk %}">{% trans 'delete' %}</a>
            </td>
        </tr>
    {% empty %}
        <tr><td colspan="3">{{ _('No authentication devices of this type are configured') }}</td</tr>
    {% endfor %}
    </tbody>
</table>
</div>
</div>

kleides_mfa/templates/kleides_mfa/device_recovery-code_list.html
{% load i18n %}

{% with recovery_device=devices.0 %}
<div class='position-relative'>
  <div class="float-right">
    <form id="kleides-mfa-create-recovery-form" action="{% url 'kleides_mfa:create' plugin.slug %}" method="post" class='d-inline-block'>{% csrf_token %}
      <button class='btn btn-primary' type='submit'>{% trans 'Generate codes' %}</button>
    </form>
    {% if recovery_device %}
      <a class='btn btn-danger' href="{% url 'kleides_mfa:delete' plugin.slug recovery_device.pk %}">{% trans 'Disable codes' %}</a>
    {% endif %}
  </div>
<h2>{{ plugin.name }}</h2>
{% trans 'If you lose your primary authentication device you can recover your account access with a recovery code.' %}

<p>
{% with tokens=recovery_device.token_set.all %}
{% if tokens %}
{% blocktrans with amount=tokens|length %}You have {{ amount }} codes available right now.{% endblocktrans %}
<button id='kleides-mfa-show-tokens'>{% trans 'Show codes' %}</button><br>
<textarea id='kleides-mfa-tokens' style='display: none; overflow: hidden; resize: none;'>{% for token in tokens %}{{ token.token }}{% if not forloop.last %}
{% endif %}{% endfor %}</textarea><br>

{% trans 'Note: If you generate new codes this will disable your current codes.' %}
{% else %}
{% trans 'You have no recovery codes available, do you want to generate some codes?' %}
{% endif %}
{% endwith %}
</p>

</div>
{% endwith %}

kleides_mfa/templates/kleides_mfa/device_totp_create_form.html
{% extends "kleides_mfa/device_create_form.html" %}

{% load i18n static %}

{% block extra_js %}
<script src="{% static 'js/kleides_mfa/jquery.qrcode.min.js' %}" integrity="sha512-NFUcDlm4V+a2sjPX7gREIXgCSFja9cHtKPOL1zj6QhnE0vcY695MODehqkaGYTLyL2wxe/wtr4Z49SvqXq12UQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
jQuery(function ($) {
    $('#qrcode').qrcode({width: 200, height: 200,text: "{{ form.instance.config_url|escapejs }}"});
});
</script>
{% endblock extra_js %}

{% block form_description %}
<div id="qrcode"></div>

<p>
{% blocktrans with url=form.instance.config_url %}
Scan the QR code with your authentication app or visit the
<a href="{{ url }}">configuration url</a> to import it on your mobile device.<br>
<br>
Then enter the token generated by the app.
{% endblocktrans %}
</p>
{% endblock form_description %}

kleides_mfa/templates/kleides_mfa/device_verify_form.html
{% extends "kleides_mfa/base.html" %}

{% load i18n %}

{% block content %}
<h1>{% blocktrans with name=device.name %}Verify {{ name }}{% endblocktrans %}</h1>

{% block form_description %}{% endblock form_description %}

<form id="kleides-mfa-verify-form" action="" method="post" novalidate>{% csrf_token %}
    {% include "kleides_mfa/form.html" %}

    {% if plugin.show_verify_button %}
    <button class='btn btn-primary' type='submit'>{% trans 'Verify' %}</button>
    {% endif %}
    <div>
      <button class="btn btn-secondary dropdown-toggle" type="button" id="kleides-mfa-alternate-methods" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% trans 'Other methods' %}
      </button>
      <div class="dropdown-menu" aria-labelledby="kleides-mfa-alternate-methods">
        {% for plugin, device in user_devices %}
        <a class="dropdown-item" href="{% url 'kleides_mfa:verify' plugin.slug device.pk %}?next={{ next|urlencode }}">{{ device.name }}</a>
        {% endfor %}
      </div>
    </div>

</form>
{% endblock content %}

kleides_mfa/templates/kleides_mfa/form.html
{{ form }}

kleides_mfa/templates/kleides_mfa/login.html
{% extends "kleides_mfa/base.html" %}

{% load i18n %}

{% block content %}
<h1>{% trans 'Login' %}</h1>

{% block form_description %}{% endblock form_description %}

<form id="kleides-mfa-form" action="" method="post" novalidate>{% csrf_token %}
    {% include "kleides_mfa/form.html" %}

    <button class='btn btn-primary' type='submit'>{% trans 'Login' %}</button>
</form>
{% endblock content %}

kleides_mfa/templates/kleides_mfa/plugin_list.html
{% extends "kleides_mfa/base.html" %}

{% load i18n static %}

{% block content %}
<h1>{% trans '2 Step Authentication' %}</h1>
<p>
{% trans 'These are your 2 step authentication methods.' %}
</p>

{% for plugin, devices in plugins %}
    {% include plugin.device_list_template|default:"kleides_mfa/device_list.html" %}
{% endfor %}
{% endblock content %}


{% block extra_js %}
{% for plugin, devices in plugins %}
{% if plugin.device_list_javascript %}
    <script type="text/javascript" src="{% static plugin.device_list_javascript %}"></script>
{% endif %}
{% endfor %}
{% endblock extra_js %}